# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:  
- master  
  
pool:  
  vmImage: 'ubuntu-latest'  
  
steps:  
- task: NodeTool@0  
  inputs:  
    versionSpec: '12.x'  
  displayName: 'Install Node.js 12.x'  
- task: Npm@1  
  displayName: 'Angular CLI'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install @angular/cli@7.3.1'  
- task: Npm@1  
  displayName: 'npm install'  
  inputs:  
    verbose: false  
  
- task: Npm@1  
  displayName: Build  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'run-script build'  
  
- task: CopyPublishBuildArtifacts@1  
  displayName: 'Copy Publish Artifact: test'  
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: test  
    ArtifactType: Container  
  
- task: DownloadPipelineArtifact@2  
  displayName: 'Download Pipeline Artifact'  
  inputs:  
    targetPath: ' $(Build.ArtifactStagingDirectory)/dist/AngularTest'