# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:  
- master  
  
pool:  
  vmImage: 'ubuntu-latest'  
  
steps:  
- task: NodeTool@0  
  inputs:  
    versionSpec: '12.x'  
  displayName: 'Install Node.js 12.x'  
- task: Npm@1  
  displayName: 'Angular CLI'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install @angular/cli@7.3.1'  
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './'
  
- task: CopyPublishBuildArtifacts@1  
  displayName: 'Copy Publish Artifact: test'  
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: test  
    ArtifactType: Container  

- task: CmdLine@2
  displayName: 'install firebase tools'
  inputs:
    script: 'npm install -g firebase-tools'
    workingDirectory: '$(Agent.ToolsDirectory)'

- task: CmdLine@2
  displayName: 'npm run build'
  inputs:
    script: 'npm run build'

- task: DownloadPipelineArtifact@2  
  displayName: 'Download Pipeline Artifact'  
  inputs:  
    targetPath: ' $(Build.ArtifactStagingDirectory)/dist/AngularTest'

- task: CmdLine@2
  displayName: 'firebase publish -m "$(Build.BuildNumber)"'    
  inputs:
    script: 'firebase deploy --token "$(FIREBASE_TOKEN)" -m '
    workingDirectory: './'
  

